# SPDX-FileCopyrightText: 2023 Lennart Heimbs <lennart@heimbs.me>
#
# SPDX-License-Identifier: MIT

---
name: super-linter

on:
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: false
          FILTER_REGEX_EXCLUDE: ".*src/test/resources.*"
